
module.exports = {
  primaryColor: '#E1E1E1',
  primaryBackgroundColor: '#000',
  primarySelectionBackgroundColor: '#1467b1',
  primarySelectionColor: '#FFFFFF',
  primaryHoverColor: '#FFFFFF',
  primaryHoverBackgroundColor: '#10518a',
  formPrimaryColor: '#ffc40d',
  secondaryColor: '#adacac',
  secondaryBackgroundColor: '#1D1D1D',
  tertiaryColor: '#FFFFFF',
  tertiaryBackgroundColor: '#296ba7',
  tertiaryBackgroundColorTarget: '#323c47',
  secondaryHoverColor: '#c6c6c6',
  secondaryHoverBackgroundColor: '#3a465f',
  alternativeHoverColor: '#4CAF50',
  highlightColor: '#3397ea',
  scrollBarThumbBackgroundColor: '#52565A',
  scrollBarThumbHoverBackgroundColor: '#A9ABAD',
  scrollBarThumbShadowColor: 'rgba(0, 0, 0, 0.2)',
  scrollBarTrackBackgroundColor: '#282829',
  tabTitlesBackgroundColor: '#1D1D1D',
  tabPaneBackgroundColor: '#1D1D1D',
  tabTitleBackgroundColor: '#121212',
  tabTitleBorderColor: '#E6E6E6',
  controlsBackgroundColor: '#2A2A2A',
  controlsColor: '#AFAFAF',
  controlsBorderColor: '#505050',
  previewBackgroundColor: '#1D1D1D',
  propertyTitleColor: '#AFAFAF',
  propertyTitleBackgroundColor: '#353434',
  propertyTitleExpandedColor: '#FFFFFF',
  propertyTitleExpandedBackgroundColor: '#296ba7',
  propertyTitleHoverColor: '#FFFFFF',
  propertyTitleHoverBackgroundColor: '#10518a',
  entityTreeButtonColor: '#fbfbfb',
  entityTreeButtonBackgroundColor: '#1D1D1D',
  entityTreeButtonBorderColor: '#FFFFFF',
  entityTreeButtonHoverColor: '#fbfbfb',
  entityTreeButtonHoverBackgroundColor: '#3a465f',
  contextMenuBackgroundColor: '#3a3a3a',
  contextMenuButtonColor: '#bdbaba',
  contextMenuButtonDisabledColor: '#7d8a98',
  contextMenuButtonHoverColor: '#FFFFFF',
  contextMenuButtonHoverBackgroundColor: '#10518a'
}
