
module.exports = {
  'primary-color': '#E1E1E1',
  'primary-backgroundColor': '#000',
  'primary-selection-backgroundColor': '#1467b1',
  'primary-selection-color': '#FFFFFF',
  'primary-hover-color': '#FFFFFF',
  'primary-hover-backgroundColor': '#10518a',
  'secondary-color': '#adacac',
  'secondary-backgroundColor': '#1D1D1D',
  'secondary-hover-backgroundColor': '#3a465f',
  'alternative-backgroundColor': '#296ba7',
  'formPrimary-color': '#ffc40d',
  'button-color': '#FFFFFF',
  'button-shadowColor': 'rgba(0, 0, 0, 0)',
  'button-active-shadowColor': 'rgba(0, 0, 0, 0.6)',
  'button-confirmation-backgroundColor': '#008CBA',
  'button-danger-backgroundColor': '#FCBE59',
  'headings-color': '#1467b1',
  'table-color': '#E1E1E1',
  'table-heading-backgroundColor': '#000',
  'table-heading-borderColor': '#ddd',
  'table-row-backgroundColor': '#000',
  'table-row-borderColor': '#FFFFFF',
  'table-row-active-backgroundColor': '#10518a',
  'table-row-active-color': '#FFFFFF',
  'table-row-hover-backgroundColor': '#3a465f',
  'table-row-hover-color': '#FFFFFF',
  'table-selection-backgroundColor': '#151515',
  'table-selection-color': '#E1E1E1',
  'resizer-backgroundColor': '#000',
  'resizer-borderColor': 'rgba(255, 255, 255, 0)',
  'resizer-hover-borderColor': 'rgba(0, 0, 0, 0.5)',
  'resizer-icons-color': '#adacac',
  'resizer-icons-hover-color': '#1467b1',
  'resizer-paneHolder-color': '#FFFFFF',
  'resizer-collapsed-backgroundColor': '#adacac',
  'resizer-collapsed-hover-backgroundColor': '#10518a',
  'scrollBar-thumb-backgroundColor': '#52565A',
  'scrollBar-thumb-hover-backgroundColor': '#A9ABAD',
  'scrollBar-track-backgroundColor': '#282829',
  'toolbar-color': '#FFFFFF',
  'toolbar-backgroundColor': '#296ba7',
  'toolbar-target-backgroundColor': '#323c47',
  'toolbar-button-disabled-color': '#adacac',
  'toolbar-button-hover-backgroundColor': '#10518a',
  'toolbar-button-hover-color': '#FFFFFF',
  'toolbar-popup-backgroundColor': '#424c57',
  'toolbar-popup-hover-backgroundColor': '#10518a',
  'tab-titles-backgroundColor': '#1D1D1D',
  'tab-titles-borderColor': '#10518a',
  'tab-pane-backgroundColor': '#1D1D1D',
  'tab-title-backgroundColor': '#121212',
  'tab-title-borderColor': '#E6E6E6',
  'tab-title-active-backgroundColor': '#1467b1',
  'tab-title-active-color': '#FFFFFF',
  'tab-title-hover-backgroundColor': '#10518a',
  'tab-title-hover-color': '#FFFFFF',
  'tab-close-color': '#adacac',
  'tab-close-hover-backgroundColor': '#3a465f',
  'controls-backgroundColor': '#2A2A2A',
  'controls-color': '#AFAFAF',
  'controls-borderColor': '#505050',
  'controls-hover-borderColor': '#1467b1',
  'controls-list-hover-backgroundColor': '#3a465f',
  'controls-list-hover-color': '#FFFFFF',
  'modal-color': '#E1E1E1',
  'modal-overlay-backgroundColor': 'rgba(0, 0, 0, 0.6)',
  'modal-backgroundColor': '#1D1D1D',
  'modal-shadowColor': 'rgba(0, 0, 0, 0.3)',
  'modal-close-color': '#adacac',
  'modal-close-hover-color': '#E1E1E1',
  'preview-backgroundColor': '#1D1D1D',
  'property-heading-backgroundColor': '#10518a',
  'property-heading-color': '#FFFFFF',
  'property-title-color': '#AFAFAF',
  'property-title-backgroundColor': '#353434',
  'property-title-expanded-color': '#FFFFFF',
  'property-title-expanded-backgroundColor': '#296ba7',
  'property-title-hover-color': '#FFFFFF',
  'property-title-hover-backgroundColor': '#10518a',
  'property-panel-backgroundColor': '#1D1D1D',
  'entityTree-color': '#E1E1E1',
  'entityTree-backgroundColor': '#1D1D1D',
  'entityTree-outlineColor': '#296ba7',
  'entityTree-node-active-backgroundColor': '#1467b1',
  'entityTree-node-active-color': '#FFFFFF',
  'entityTree-node-hover-backgroundColor': '#3a465f',
  'entityTree-node-hover-color': '#FFFFFF',
  'entityTree-collapseIcon-collapsed-color': '#c6c6c6',
  'entityTree-collapseIcon-color': '#1467b1',
  'entityTree-collapseIcon-hover-color': '#1467b1',
  'entityTree-icon-color': '#adacac',
  'entityTree-icon-hover-color': '#10518a',
  'entityTree-highlight-color': '#3397ea',
  'entityIcon-color': '#F16220',
  'entityTree-button-color': '#fbfbfb',
  'entityTree-button-backgroundColor': '#1D1D1D',
  'entityTree-button-borderColor': '#FFFFFF',
  'entityTree-button-hover-color': '#fbfbfb',
  'entityTree-button-hover-backgroundColor': '#3a465f',
  'entityTree-button-active-borderColor': '#1467b1',
  'contextMenu-backgroundColor': '#3a3a3a',
  'contextMenu-button-color': '#bdbaba',
  'contextMenu-button-disabled-color': '#7d8a98',
  'contextMenu-button-hover-color': '#FFFFFF',
  'contextMenu-button-hover-backgroundColor': '#10518a',
  'entityFinder-input-shadowColor': 'rgba(0, 0, 0, 0.2)',
  'entityFinder-input-hover-borderColor': '#d9d9d9',
  'entityFinder-results-shadowColor': 'rgba(0, 0, 0, 0.1)',
  'entityFinder-results-borderColor': '#adacac',
  'entityFinder-results-item-active-color': '#fff',
  'entityFinder-results-item-active-backgroundColor': '#1467b1',
  'popover-backgroundColor': '#3a3a3a',
  'popover-borderColor': 'rgba(0,0,0,0.2)',
  'popover-shadowColor': 'rgba(0,0,0,0.15)'
}
