
module.exports = {
  primaryColor: '#2f2f2f',
  primaryBackgroundColor: '#FFFFFF',
  primarySelectionBackgroundColor: '#007ACC',
  primarySelectionColor: '#FFFFFF',
  primaryHoverColor: '#FFFFFF',
  primaryHoverBackgroundColor: '#1C97EA',
  formPrimaryColor: '#ffc40d',
  secondaryColor: '#d9d9d9',
  secondaryBackgroundColor: '#F6F6F6',
  tertiaryColor: '#FFFFFF',
  tertiaryBackgroundColor: 'rgb(85, 85, 85)',
  tertiaryBackgroundColorTarget: '#323c47',
  secondaryHoverColor: '#c6c6c6',
  secondaryHoverBackgroundColor: '#73a2ff',
  alternativeHoverColor: '#4CAF50',
  highlightColor: '#3397ea',
  scrollBarThumbBackgroundColor: '#C1C1C1',
  scrollBarThumbHoverBackgroundColor: '#7D7D7D',
  scrollBarTrackBackgroundColor: '#FAFAFA',
  tabTitlesBackgroundColor: '#FEFEFE',
  tabPaneBackgroundColor: '#FEFEFE',
  tabTitleBackgroundColor: '#FEFEFE',
  tabTitleBorderColor: '#E6E6E6',
  controlsBackgroundColor: '#FFFFFF',
  controlsColor: '#000000',
  controlsBorderColor: '#d9d9d9',
  previewBackgroundColor: 'rgba(0, 0, 0, 0)',
  propertyTitleColor: '#2f2f2f',
  propertyTitleBackgroundColor: '#d9d9d9',
  propertyTitleExpandedColor: '#F6F6F6',
  propertyTitleExpandedBackgroundColor: '#007ACC',
  propertyTitleHoverColor: '#FFFFFF',
  propertyTitleHoverBackgroundColor: '#1C97EA',
  entityTreeButtonColor: '#494949',
  entityTreeButtonBackgroundColor: '#F6F6F6',
  entityTreeButtonBorderColor: '#e2e2e2',
  entityTreeButtonHoverColor: '#494949',
  entityTreeButtonHoverBackgroundColor: '#FFFFFF',
  contextMenuBackgroundColor: '#d9d9d9',
  contextMenuButtonColor: '#2f2f2f',
  contextMenuButtonDisabledColor: '#7d8a98',
  contextMenuButtonHoverColor: '#FFFFFF',
  contextMenuButtonHoverBackgroundColor: '#1C97EA'
}
