
module.exports = {
  'primary-color': '#2f2f2f',
  'primary-backgroundColor': '#FFFFFF',
  'primary-selection-backgroundColor': '#007ACC',
  'primary-selection-color': '#FFFFFF',
  'primary-hover-color': '#FFFFFF',
  'primary-hover-backgroundColor': '#1C97EA',
  'secondary-color': '#d9d9d9',
  'secondary-backgroundColor': '#F6F6F6',
  'secondary-hover-backgroundColor': '#73a2ff',
  'alternative-backgroundColor': 'rgb(85, 85, 85)',
  'formPrimary-color': '#ffc40d',
  'button-color': '#FFFFFF',
  'button-shadowColor': 'rgba(0, 0, 0, 0)',
  'button-active-shadowColor': 'rgba(0, 0, 0, 0.6)',
  'button-confirmation-backgroundColor': '#008CBA',
  'button-danger-backgroundColor': '#FCBE59',
  'headings-color': '#007ACC',
  'table-color': '#2f2f2f',
  'table-heading-backgroundColor': '#FFFFFF',
  'table-heading-borderColor': '#ddd',
  'table-row-backgroundColor': '#FFFFFF',
  'table-row-borderColor': '#FFFFFF',
  'table-row-active-backgroundColor': '#1C97EA',
  'table-row-active-color': '#FFFFFF',
  'table-row-hover-backgroundColor': '#73a2ff',
  'table-row-hover-color': '#FFFFFF',
  'table-selection-backgroundColor': '#eeeeee',
  'table-selection-color': '#2f2f2f',
  'resizer-backgroundColor': '#000',
  'resizer-borderColor': 'rgba(255, 255, 255, 0)',
  'resizer-hover-borderColor': 'rgba(0, 0, 0, 0.5)',
  'resizer-icons-color': '#d9d9d9',
  'resizer-icons-hover-color': '#007ACC',
  'resizer-paneHolder-color': '#FFFFFF',
  'resizer-collapsed-backgroundColor': '#d9d9d9',
  'resizer-collapsed-hover-backgroundColor': '#1C97EA',
  'scrollBar-thumb-backgroundColor': '#C1C1C1',
  'scrollBar-thumb-hover-backgroundColor': '#7D7D7D',
  'scrollBar-track-backgroundColor': '#FAFAFA',
  'toolbar-color': '#FFFFFF',
  'toolbar-backgroundColor': 'rgb(85, 85, 85)',
  'toolbar-target-backgroundColor': '#323c47',
  'toolbar-button-disabled-color': '#d9d9d9',
  'toolbar-button-hover-backgroundColor': '#1C97EA',
  'toolbar-button-hover-color': '#FFFFFF',
  'toolbar-popup-backgroundColor': '#424c57',
  'toolbar-popup-hover-backgroundColor': '#1C97EA',
  'tab-titles-backgroundColor': '#FEFEFE',
  'tab-titles-borderColor': '#1C97EA',
  'tab-pane-backgroundColor': '#FEFEFE',
  'tab-title-backgroundColor': '#FEFEFE',
  'tab-title-borderColor': '#E6E6E6',
  'tab-title-active-backgroundColor': '#007ACC',
  'tab-title-active-color': '#FFFFFF',
  'tab-title-hover-backgroundColor': '#1C97EA',
  'tab-title-hover-color': '#FFFFFF',
  'tab-close-color': '#d9d9d9',
  'tab-close-hover-backgroundColor': '#73a2ff',
  'controls-backgroundColor': '#FFFFFF',
  'controls-color': '#000000',
  'controls-borderColor': '#d9d9d9',
  'controls-hover-borderColor': '#007ACC',
  'controls-list-hover-backgroundColor': '#73a2ff',
  'controls-list-hover-color': '#FFFFFF',
  'modal-color': '#2f2f2f',
  'modal-overlay-backgroundColor': 'rgba(0, 0, 0, 0.6)',
  'modal-backgroundColor': '#F6F6F6',
  'modal-shadowColor': 'rgba(0, 0, 0, 0.3)',
  'modal-close-color': '#d9d9d9',
  'modal-close-hover-color': '#2f2f2f',
  'preview-backgroundColor': 'rgba(0, 0, 0, 0)',
  'property-heading-backgroundColor': '#1C97EA',
  'property-heading-color': '#FFFFFF',
  'property-title-color': '#2f2f2f',
  'property-title-backgroundColor': '#d9d9d9',
  'property-title-expanded-color': '#F6F6F6',
  'property-title-expanded-backgroundColor': '#007ACC',
  'property-title-hover-color': '#FFFFFF',
  'property-title-hover-backgroundColor': '#1C97EA',
  'property-panel-backgroundColor': '#F6F6F6',
  'entityTree-color': '#2f2f2f',
  'entityTree-backgroundColor': '#F6F6F6',
  'entityTree-outlineColor': 'rgb(85, 85, 85)',
  'entityTree-node-active-backgroundColor': '#007ACC',
  'entityTree-node-active-color': '#FFFFFF',
  'entityTree-node-hover-backgroundColor': '#73a2ff',
  'entityTree-node-hover-color': '#FFFFFF',
  'entityTree-collapseIcon-collapsed-color': '#c6c6c6',
  'entityTree-collapseIcon-color': '#007ACC',
  'entityTree-collapseIcon-hover-color': '#007ACC',
  'entityTree-icon-color': '#d9d9d9',
  'entityTree-icon-hover-color': '#1C97EA',
  'entityTree-highlight-color': '#3397ea',
  'entityIcon-color': '#F16220',
  'entityTree-button-color': '#494949',
  'entityTree-button-backgroundColor': '#F6F6F6',
  'entityTree-button-borderColor': '#e2e2e2',
  'entityTree-button-hover-color': '#494949',
  'entityTree-button-hover-backgroundColor': '#FFFFFF',
  'entityTree-button-active-borderColor': '#007ACC',
  'contextMenu-backgroundColor': '#d9d9d9',
  'contextMenu-button-color': '#2f2f2f',
  'contextMenu-button-disabled-color': '#7d8a98',
  'contextMenu-button-hover-color': '#FFFFFF',
  'contextMenu-button-hover-backgroundColor': '#1C97EA',
  'entityFinder-input-shadowColor': 'rgba(0, 0, 0, 0.2)',
  'entityFinder-input-hover-borderColor': '#d9d9d9',
  'entityFinder-results-shadowColor': 'rgba(0, 0, 0, 0.1)',
  'entityFinder-results-borderColor': '#d9d9d9',
  'entityFinder-results-item-active-color': '#fff',
  'entityFinder-results-item-active-backgroundColor': '#007ACC',
  'popover-backgroundColor': '#FFFFFF',
  'popover-borderColor': 'rgba(0,0,0,0.2)',
  'popover-shadowColor': 'rgba(0,0,0,0.15)'
}
