
module.exports = {
  'primary-color': '#2f2f2f',
  'primary-backgroundColor': '#FFFFFF',
  'primary-selection-backgroundColor': '#007ACC',
  'primary-selection-color': '#FFFFFF',
  'primary-hover-color': '#FFFFFF',
  'primary-hover-backgroundColor': '#1C97EA',
  'secondary-color': '#d9d9d9',
  'secondary-backgroundColor': '#F6F6F6',
  'secondary-hover-color': '#c6c6c6',
  'secondary-hover-backgroundColor': '#73a2ff',
  'tertiary-color': '#FFFFFF',
  'tertiary-backgroundColor': 'rgb(85, 85, 85)',
  'tertiary-target-backgroundColor': '#323c47',
  'highlight-color': '#3397ea',
  'formPrimary-color': '#ffc40d',
  'scrollBar-thumb-backgroundColor': '#C1C1C1',
  'scrollBar-thumb-hover-backgroundColor': '#7D7D7D',
  'scrollBar-track-backgroundColor': '#FAFAFA',
  'tab-titles-backgroundColor': '#FEFEFE',
  'tab-pane-backgroundColor': '#FEFEFE',
  'tab-title-backgroundColor': '#FEFEFE',
  'tab-title-borderColor': '#E6E6E6',
  'controls-backgroundColor': '#FFFFFF',
  'controls-color': '#000000',
  'controls-borderColor': '#d9d9d9',
  'preview-backgroundColor': 'rgba(0, 0, 0, 0)',
  'property-title-color': '#2f2f2f',
  'property-title-backgroundColor': '#d9d9d9',
  'property-title-expanded-color': '#F6F6F6',
  'property-title-expanded-backgroundColor': '#007ACC',
  'property-title-hover-color': '#FFFFFF',
  'property-title-hover-backgroundColor': '#1C97EA',
  'entityTree-button-color': '#494949',
  'entityTree-button-backgroundColor': '#F6F6F6',
  'entityTree-button-borderColor': '#e2e2e2',
  'entityTree-button-hover-color': '#494949',
  'entityTree-button-hover-backgroundColor': '#FFFFFF',
  'contextMenu-backgroundColor': '#d9d9d9',
  'contextMenu-button-color': '#2f2f2f',
  'contextMenu-button-disabled-color': '#7d8a98',
  'contextMenu-button-hover-color': '#FFFFFF',
  'contextMenu-button-hover-backgroundColor': '#1C97EA'
}
